name: CI

on:
  push:

jobs:
  stack:
    name: ghc ${{ matrix.ghc }} / ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.4.8', '9.6.5', '9.8.2']
        platform: [ubuntu-latest, windows-latest]

    steps:
    - uses: haskell-actions/setup@v2
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/checkout@v4
      name: Clone project

    - name: Build
      run: cabal build

    - name: Test
      run: cabal test
